### ISSUE TITLE
Works on multisite

### ISSUE THREAD

**Issue by samikeijonen** [devinsays/edd-theme-updater#10]
I've never been able to get updates in multisite. Not for my own themes or any EDD add-ons.

But this one worked on multisite also in my localhost test! I hope it'll work on live site also. That's a huge bonus in my eyes.

**Comment by devinsays** [comment]
That's great!  Thanks for testing.

I noticed that this project:
https://github.com/Yoast/License-Manager

Has a number of checks for multisite:
https://github.com/Yoast/License-Manager/blob/master/class-product.php

**Comment by samikeijonen** [comment]
I'm not 100% sure do I trust Yoast plugin updater on multisite:) That's because in my customer site updater never worked when we use one of his plugins on multisite. But that could be fixed by now, so let's take best parts from there definitely.
