### ISSUE TITLE
Extract Strings for Filtering/Manipulation

### ISSUE THREAD

**Issue by devinsays** [devinsays/edd-theme-updater#11]
I think it would be helpful to have all the strings defined in one place.  This makes them easier to edit or filter.  Started work on this with: https://github.com/devinsays/edd-theme-updater/commit/01304d8b9a26e730c8deb7dbc003a62f6a27fc2b

**Comment by samikeijonen** [comment]
Looks good and seems easier.

**Comment by devinsays** [comment]
4526754637abc8cdc0ff9ef61ca4ae5bc9520ac8 extracts the remaining strings and requires them to be passed when EDD_Theme_Updater_Admin is set up.  This allows them to be easily overridden and translated, but I'm also not sure this is the best approach.

Here's the alternate I considered:

### Put all the strings into a function that is filtered

When a string is needed, the function is called and filters can be applied by the theme (or plugin).  

Questions for this approach:
- What textdomain should be used for those strings? (pass textdomain as a variable, use unique textdomain, have theme author change textdomain)

Benefits: Most developers will not be changing the strings, so it makes sense not to surface them in theme-updater.php if they're not needed.

This approach can also be combined with approach I'm currently using.  Passing the string arguments from theme-updater.php would just be optional.

**Comment by pippinsplugins** [comment]
Text domains should never be passed as variables: http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

I love the idea of strings all being easily accessible.

**Comment by devinsays** [comment]
Do you like them surfaced in the config? https://github.com/devinsays/edd-theme-updater/blob/master/updater/theme-updater.php

Or do you think it would make more sense to bury them in the class (easily overridden + filterable)?

**Comment by devinsays** [comment]
When the .pot file is generated- it doesn't seem to matter what the text domain is set as.  Moved the strings back into the class.  This is the way I'd prefer to do it as long as long as it doesn't mess up anything for translators. 0455746
