### ISSUE TITLE
Theme version

### ISSUE THREAD

**Issue by samikeijonen** [devinsays/edd-theme-updater#2]
Do you think it's too heavy to get theme version using `wp_get_theme` function?

https://github.com/samikeijonen/mina-olen/blob/master/admin/functions-admin.php#L12

I always forgot to update theme version if it's in several places.

**Comment by devinsays** [comment]
I'm not sure how heavy that function is.  But, this code makes it so it just needs to be updated in one place (inside prefix_updater_settings).  If you don't want to do that, just remove the variable and it will fallback to wp_get_theme for the version.

**Comment by samikeijonen** [comment]
For me in two places can be too much:) Meaning in style.css and in updater.

**Comment by devinsays** [comment]
I actually just define the version in package.json and have a Grunt task update it everywhere it's required which is how I'll approach it for my projects.

See: https://github.com/devinsays/platform

If you want to fork and remove I think that's fine.  It's probably only slightly more performant to define it.

**Comment by samikeijonen** [comment]
I've been also start using Grunt so I'll check this out.
