### ISSUE TITLE
List Site Counts (for activated license)

### ISSUE THREAD

**Issue by devinsays** [devinsays/edd-theme-updater#4]
From @samikeijonen:

https://gist.github.com/samikeijonen/be0ead5baa143524c171#file-theme-updater-php-L129

**Comment by samikeijonen** [comment]
That message doesn't have to be in separate TH and TD so your original idea is just fine. But I'd like to have site count in there. 

https://gist.github.com/samikeijonen/be0ead5baa143524c171#file-theme-updater-php-L331

We could make the message better. Now it's like License key is active. Expires 1.1.2015. Activated sites 1 / 1. 

It could be more like License key is active and expires 1.1.2015. You have 1 / 1 sites activated.

I can do pull request and some general cleaning for this.

**Comment by devinsays** [comment]
Thanks for the pull request on this.  Closing.
