### ISSUE TITLE
Move admin functions into a separate file

### ISSUE THREAD

**Issue by devinsays** [devinsays/edd-theme-updater#5]
Ideally the developer should just need to put in the custom settings, and everything else is abstracted.

This end, I'd like to move all the admin page functions into a separate file.  I'd also like to wrap all of these in a class and make all the strings filterable.

**Comment by samikeijonen** [comment]
I like where this is heading

**Comment by devinsays** [comment]
There's even more abstraction into this latest commit:
https://github.com/devinsays/edd-theme-updater/commit/a686e5499b04734375cf92c989da17fd743a704b

Open a new ticket for specific items if you see more places to improve.  I'm sure there are some.
